
--Intial table template
CREATE TABLE analytics.retail_clean(
    row_no bigserial primary key,   
  transaction_id        text,
  customer_id           text,
  name                  text,
  email                 text,
  phone                 text,
  address               text,
  city                  text,
  state                 text,
  zipcode               text,
  country               text,
  age                   text,
  gender                text,
  income                text,
  customer_segment      text,
  date                  text,
  year                  text,
  month                 text,
  time                  text,
  total_purchases       text,
  amount                text,
  total_amount          text,
  product_category      text,
  product_brand         text,
  product_type          text,
  feedback              text,
  shipping_method       text,
  payment_method        text,
  order_status          text,
  ratings               text,
  products              text
);

--Final Table template
CREATE TABLE analytics.retail_clean_typed AS
SELECT
    transaction_id,
    customer_id,
    name,
    email,
    phone,
    address,
    city,
    state,
    zipcode,
    country,
    CAST(age AS INTEGER) AS age,
    gender,
    income,
    customer_segment,
    TO_DATE(date, 'YYYY-MM-DD') AS date,
    CAST("year" AS INTEGER) AS year,
    month,
    TO_TIMESTAMP(time, 'HH24:MI:SS')::TIME AS time,
    CAST(total_purchases AS INTEGER) AS total_purchases,
    CAST(amount AS NUMERIC(10,2)) AS amount,
    CAST(total_amount AS NUMERIC(10,2)) AS total_amount,
    product_category,
    product_brand,
    product_type,
    feedback,
    shipping_method,
    payment_method,
    order_status,
    CAST(ratings AS INTEGER) AS ratings,
    products
FROM analytics.retail_clean;